import { Batch } from "./types";

export const BATCHES: Batch[] = [
  {
    id: "batch-1",
    name: "七級",
    description: "Random 10s — Building fundamentals with Level 10 charts.",
    minLevel: 10.0,
    maxLevel: 10.9,
    randomCount: [7, 9],
  },
  {
    id: "batch-2",
    name: "六級",
    description: "Random 10+s — Pushing beyond Level 10 into harder territory.",
    minLevel: 10.7,
    maxLevel: 10.9,
    randomCount: [7, 9],
  },
  {
    id: "batch-3",
    name: "五級",
    description: "Random 11s — Entering Level 11 with more complex patterns.",
    minLevel: 11.0,
    maxLevel: 11.6,
    randomCount: [7, 8],
  },
  {
    id: "batch-4",
    name: "四級",
    description: "Random 11+s — Upper Level 11 challenges.",
    minLevel: 11.7,
    maxLevel: 11.9,
    randomCount: [7, 8],
  },
  {
    id: "batch-5",
    name: "三級",
    description: "Random 12.0–12.2 — Introduction to Level 12.",
    minLevel: 12.0,
    maxLevel: 12.2,
    randomCount: [7, 7],
  },
  {
    id: "batch-6",
    name: "二級",
    description: "Random 12.3–12.5 — Mid Level 12 challenges.",
    minLevel: 12.3,
    maxLevel: 12.5,
    randomCount: [7, 7],
  },
  {
    id: "batch-7",
    name: "一級",
    description: "Random 12.6–12.9 — Upper Level 12, approaching 13.",
    minLevel: 12.6,
    maxLevel: 12.9,
    randomCount: [7, 7],
  },
  {
    id: "batch-8",
    name: "初段",
    description: "Curated song list — First set of specific challenges.",
    songTitles: [
      "Barbed Eye",
      "深海少女",
      "BANG!",
      "ライアーダンサー",
      "ナイト・オブ・ナイツ (MAS)",
      "ブレインジャックシンドローム",
      "放課後ストライド",
    ],
  },
  {
    id: "batch-9",
    name: "二段",
    description: "Curated song list — Iconic rhythm game tracks.",
    songTitles: [
      "千本桜",
      "パーフェクション",
      "いちげき！のテーマ",
      "廻廻奇譚",
      "Rush-More",
      "Now or Never (MAS)",
      "トランスダンスアナーキー",
    ],
  },
  {
    id: "batch-10",
    name: "三段",
    description: "Curated song list — Intense vocal and electronic tracks.",
    songTitles: [
      "ありふれたせかいせいふく",
      "Oshama Scramble!",
      "エスオーエス",
      "分解収束テイル",
      "アンビバレンス",
      "バカ通信",
      "病み垢ステロイド",
    ],
  },
  {
    id: "batch-11",
    name: "四段",
    description: "Curated song list — A mix of elegant and aggressive charts.",
    songTitles: [
      "Sakura Fubuki",
      "華の集落、秋のお届け",
      "FLOWER (MAS)",
      "Good Bye, Mr. Jack",
      "Ultranova",
      "Jack-the-Ripper◆",
      "Lividi",
    ],
  },
  {
    id: "batch-12",
    name: "五段",
    description: "Curated song list — High-tier technical challenges.",
    songTitles: [
      "B.M.S.",
      "Halcyon (STD)",
      "Scarlet Lance",
      "花と、雪と、ドラムンベース。 (MAS)",
      "World Vanquisher",
      "HERA",
      "極圏",
    ],
  },
  {
    id: "batch-13",
    name: "六段",
    description: "Curated song list — Expert-level endurance tests.",
    songTitles: [
      "初音ミクの激唱",
      "LAMIA",
      "CITRUS MONSTER",
      "Credits",
      "雷切-RAIKIRI- (MAS)",
      "TiamaT:F minor",
      "Åntinomiε",
    ],
  },
  {
    id: "batch-14",
    name: "七段",
    description: "Curated song list — Near-peak difficulty charts.",
    songTitles: [
      "End Time",
      "Lia=Fail",
      "Re:Unknown X",
      "GIGANTØMAKHIA",
      "KHYMΞXΛ",
      "怒槌",
      "Glorious Crown",
    ],
  },
  {
    id: "batch-15",
    name: "八段",
    description: "Curated song list — The hardest tier.",
    songTitles: [
      "WiPE OUT MEMORIES",
      "氷滅の135小節",
      "Divide et impera!",
      "7 Wonders",
      "躯樹の墓守",
      "sølips",
      "PANDORA PARADOXXX (MAS)",
    ],
  },
  {
    id: "batch-16",
    name: "皆伝",
    description: "Curated song list — The pinnacle.",
    songTitles: [
      "raputa",
      "World's end loneliness",
      "the EmpErroR",
      "PANDORA PARADOXXX",
      "系ぎて",
      "QZKago Requiem",
    ],
  },
];
