import { Batch } from "./types";

export const BATCHES: Batch[] = [
  {
    id: "batch-1",
    name: "七級",
    description: "Random 10s — Building fundamentals with Level 10 charts.",
    minLevel: 10.0,
    maxLevel: 10.9,
    randomCount: [7, 9],
  },
  {
    id: "batch-2",
    name: "六級",
    description: "Random 10+s — Pushing beyond Level 10 into harder territory.",
    minLevel: 10.7,
    maxLevel: 10.9,
    randomCount: [7, 9],
  },
  {
    id: "batch-3",
    name: "五級",
    description: "Random 11s — Entering Level 11 with more complex patterns.",
    minLevel: 11.0,
    maxLevel: 11.6,
    randomCount: [7, 8],
  },
  {
    id: "batch-4",
    name: "四級",
    description: "Random 11+s — Upper Level 11 challenges.",
    minLevel: 11.7,
    maxLevel: 11.9,
    randomCount: [7, 8],
  },
  {
    id: "batch-5",
    name: "三級",
    description: "Random 12.0–12.2 — Introduction to Level 12.",
    minLevel: 12.0,
    maxLevel: 12.2,
    randomCount: [7, 7],
  },
  {
    id: "batch-6",
    name: "二級",
    description: "Random 12.3–12.5 — Mid Level 12 challenges.",
    minLevel: 12.3,
    maxLevel: 12.5,
    randomCount: [7, 7],
  },
  {
    id: "batch-7",
    name: "一級",
    description: "Random 12.6–12.9 — Upper Level 12, approaching 13.",
    minLevel: 12.6,
    maxLevel: 12.9,
    randomCount: [7, 7],
  },
  {
    id: "batch-8",
    name: "初段",
    description: "Curated song list — First set of specific challenges.",
    songTitles: [
      "Barbed Eye",
      "深海少女",
      "BANG!",
      "ライアーダンサー",
      "ナイト・オブ・ナイツ (MAS)",
      "ブレインジャックシンドローム",
      "放課後ストライド",
    ],
  },
  {
    id: "batch-9",
    name: "二段",
    description: "Curated song list — Iconic rhythm game tracks.",
    songTitles: [
      "千本桜",
      "パーフェクション",
      "いちげき！のテーマ",
      "廻廻奇譚",
      "Rush-More",
      "Now or Never (MAS)",
      "トランスダンスアナーキー",
    ],
  },
  {
    id: "batch-10",
    name: "三段",
    description: "Curated song list — Intense vocal and electronic tracks.",
    songTitles: [
      "ありふれたせかいせいふく",
      "Oshama Scramble!",
      "エスオーエス",
      "分解収束テイル",
      "アンビバレンス",
      "バカ通信",
      "病み垢ステロイド",
    ],
  },
  {
    id: "batch-11",
    name: "四段",
    description: "Curated song list — A mix of elegant and aggressive charts.",
    songTitles: [
      { title: "Sakura Fubuki", tags: ["Tech", "Tricky"] },
      { title: "華の集落、秋のお届け", tags: ["Touch", "Tech"] },
      { title: "FLOWER (MAS)", tags: ["Spin", "Tech"] },
      { title: "Good Bye, Mr. Jack", tags: ["Tech", "Hold"] },
      { title: "Ultranova", tags: ["Stamina", "Balanced"] },
      { title: "Jack-the-Ripper◆", tags: ["Speed", "Tech"] },
      { title: "Lividi", tags: ["Stamina", "Tech"] }
    ],
  },
  {
    id: "batch-12",
    name: "五段",
    description: "Curated song list — High-tier technical challenges.",
    songTitles: [
      { title: "B.M.S.",                       tags: ["Tricky"] },
      { title: "Halcyon (STD)",                tags: ["Tech"] },
      { title: "Scarlet Lance", tags: ["Stamina", "Breaks"] },
      { title: "花と、雪と、ドラムンベース。 (MAS)", tags: ["Spin", "Tech"] },
      { title: "World Vanquisher",             tags: ["Stamina", "Tech"] },
      { title: "HERA",                         tags: ["Tricky", "Notes"] },
      { title: "極圏", tags: ["Speed", "Tech"] }
    ],
  },
  {
    id: "batch-13",
    name: "六段",
    description: "Curated song list — Expert-level endurance tests.",
    songTitles: [
      { title: "初音ミクの激唱",   tags: ["Speed", "Notes"] },
      { title: "LAMIA", tags: ["Breaks", "Stamina"] },
      { title: "CITRUS MONSTER", tags: ["Speed"] },
      { title: "Credits", tags: ["Tricky"] },
      { title: "雷切-RAIKIRI- (MAS)",   tags: ["Tech"] },
      { title: "TiamaT:F minor", tags: ["Speed", "Tech"] },
      { title: "Åntinomiε", tags: ["Breaks", "Speed"] }
    ],
  },
  {
    id: "batch-14",
    name: "七段",
    description: "Curated song list — Near-peak difficulty charts.",
    songTitles: [
      { title: "End Time",        tags: ["Stamina", "Notes"] },
      { title: "Lia=Fail", tags: ["Spin", "Tech"] },
      { title: "Re:Unknown X", tags: ["Notes", "Stamina"] },
      { title: "GIGANTØMAKHIA", tags: ["Breaks", "Spin"] },
      { title: "KHYMΞXΛ", tags: ["Breaks", "Tricky"] },
      { title: "怒槌", tags: ["Spin", "Stamina"] },
      { title: "Glorious Crown", tags: ["Spin"] }
    ],
  },
  {
    id: "batch-15",
    name: "八段",
    description: "Curated song list — The hardest tier.",
    songTitles: [
      { title: "WiPE OUT MEMORIES",   tags: ["Breaks", "Speed"] },
      { title: "氷滅の135小節", tags: ["Breaks", "Spin"] },
      { title: "Divide et impera!", tags: ["Notes", "Breaks"] },
      { title: "7 Wonders", tags: ["Stamina"] },
      { title: "躯樹の墓守", tags: ["Spin", "Tech"] },
      { title: "sølips", tags: ["Tech", "Tricky"] },
      { title: "PANDORA PARADOXXX (MAS)", tags: ["Spin", "Notes"] }
    ],
  },
  {
    id: "batch-16",
    name: "皆伝",
    description: "Curated song list — The pinnacle.",
    songTitles: [
      { title: "raputa", tags: ["Speed"] },
      { title: "World's end loneliness", tags: ["Stamina", "Tech"] },
      { title: "the EmpErroR", tags: ["Speed"] },
      { title: "PANDORA PARADOXXX", tags: ["Spin", "Notes"] }, // the prompt says PANDORA PARADOXXX again, let's keep it but actually the original had PANDORA PARADOXXX. Let's use what the prompt JSON provided, but wait. Original had PANDORA PARADOXXX. Let's look.
      { title: "系ぎて", tags: ["Spin", "Tricky"] },
      { title: "QZKago Requiem", tags: ["Spin", "Speed"] }
    ],
  },
];

export const SKILL_COLORS: Record<string, string> = {
  "Stamina": "#F09595",
  "Speed": "#FAC775",
  "Tech": "#85B7EB",
  "Spin": "#5DCAA5",
  "Breaks": "#AFA9EC",
  "Tricky": "#F0997B",
  "Touch": "#ED93B1",
  "Hold": "#B4B2A9",
  "Notes": "#97C459",
  "Balanced": "#D3D1C7"
};

export const FRAUD_CHARTS = [
  "MEGATON BLAST", "AMAZING MIGHTYYYY!!!!", "りばーぶ", "マリアをはげませ", "エピクロスの虹はもう見えない",
  "Entrance", "アマツキツネ", "Quartet Theme［Reborn］", "Oshama Scramble!", "∀",
  "色は匂へど散りぬるを", "Titania", "宛城、炎上！！", "YURUSHITE", "Sound Chimera",
  "神室雪月花", "Urban Crusher [Remix]", "System “Z”", "Pixel Voyage", "Change Our MIRAI！",
  "Change Our MIRAI!", "Bad Apple!! feat.nomico (REDALiCE Remix)", "NULCTRL", "居並ぶ穀物と溜息まじりの運送屋",
  "絡繰りドール", "KHYMΞXΛ", "ozma", "神威", "FREEDOM DiVE (tpz Overcute Remix)",
  "もぺもぺ", "Black Out", "Valsqotch", "おても☆Yan", "ケロ⑨destiny",
  "ねぇ、壊れタ人形ハ何処へ棄テらレるノ？", "前前前世", "Stardust Memories", "Paranoia",
  "Dive into The Sky ～initialized～", "下克上々", "ノイローゼ", "INFiNiTE ENERZY -Overdoze-",
  "ENERGY SYNERGY MATRIX", "Turn around", "Boys O'Clock", "カゲロウデイズ", "Flashkick",
  "すーぱーぬこになれんかった", "アンクローズ・ヒューマン", "紅星ミゼラブル～廃憶編", "阿修羅ちゃん",
  "Λzure Vixen", "幾四音-Ixion-", "Club Ibuki in Break All", "サドマミホリック",
  "Round Round Spinning Around", "The wheel to the right", "Lionheart", "Brain Power",
  "Technicians High", "Rush-More", "チューリングの跡", "最終鬼畜妹フランドール・Ｓ",
  "sølips", "[X]", "Xaleid◆scopiX", "DADDY MULK -Groove remix-", "ハジマリノピアノ",
  "バグ", "系ぎて", "FLOWER", "Hyper Active", "Scream out! -maimai SONIC WASHER Edit-",
  "KING is BACK!!", "GO BACK 2 YOUR RAVE", "CHAOS", "We Gonna Party", "FEEL the BEATS",
  "ツムギボシ", "華の集落、秋のお届け", "Outlaw's Lullaby", "Nitrous Fury",
  "患部で止まってすぐ溶ける～狂気の優曇華院", "人里に下ったアタイがいつの間にか社畜になっていた件",
  "天火明命", "Maxi", "Ultranova", "Ragnarok", "METATRON", "Lividi",
  "Love’s Theme of BADASS ～バッド・アス 愛のテーマ～", "Beat Of Mind", "Calamity Fortune",
  "conflict", "Desperado Waltz", "Maboroshi", "Grievous Lady", "花と、雪と、ドラムンベース。",
  "Halcyon", "Xevel", "CITRUS MONSTER", "Hurtling Boys", "FFT", "Axeria", "Fragrance",
  "雷切-RAIKIRI-", "零號車輛", "larva", "Alea jacta est!", "封焔の135秒", "QZKago Requiem"
];
